In [1]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in c:\users\gaj\appdata\local\programs\python\python311\lib\site-packages (2.3.0)
Requirement already satisfied: numpy>=1.23.2 in c:\users\gaj\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gaj\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gaj\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gaj\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\gaj\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
"D:\projects_Sara\analysis_real_estate_LJ\clean_GURS\new_prodaja2014.csv"

'D:\\projects_Sara\x07nalysis_real_estate_LJ\\clean_GURS\new_prodaja2014.csv'

##Loading all of the tables and joining them in one

In [10]:
df = pd.read_csv(r"prodaja2014_202507241023.csv", sep=",", encoding="utf-8",)
df1 = pd.read_csv(r"prodaja2015_202507231453.csv", sep=",", encoding="utf-8",)
df2 = pd.read_csv(r"prodaja2016_202507231442.csv", sep=",", encoding="utf-8",)
df3 = pd.read_csv(r"prodaja2017_202507241047.csv", sep=",", encoding="utf-8",)
df4 = pd.read_csv(r"prodaja2018_202507241138.csv", sep=",", encoding="utf-8",)
df5 = pd.read_csv(r"prodaja2019_202507241149.csv", sep=",", encoding="utf-8",)
df6 = pd.read_csv(r"prodaja2020_202507241157.csv", sep=",", encoding="utf-8",)
df7 = pd.read_csv(r"prodaja2021_202507241207.csv", sep=",", encoding="utf-8",)
df8 = pd.read_csv(r"prodaja2022_202507241213.csv", sep=",", encoding="utf-8",)
df9 = pd.read_csv(r"prodaja2023_202507241310.csv", sep=",", encoding="utf-8",)
df0 = pd.read_csv(r"prodaja2024_202507241308.csv", sep=",", encoding="utf-8",)

In [11]:
df1.sample(10)

,ID_POSLA,SIFRA_KO,IME_KO,OBCINA,STEVILKA_STAVBE,STEVILKA_DELA_STAVBE,NASELJE,ULICA,HISNA_STEVILKA,STEVILKA_STANOVANJA_ALI_POSLOVNEGA_PROSTORA,...,STOPNJA_DDV,DATUM_IZTEKA_LIZINGA,DATUM_PRENEHANJA_LIZINGA,OPOMBE_O_PRAVNEM_POSLU,POSREDOVANJE_NEPREMICNINSKE_AGENCIJE,DATUM_ZADNJE_SPREMEMBE_POSLA,DATUM_ZADNJE_UVELJAVITVE_POSLA,VRSTA_AKTA,TRZNOST_POSLA,LETO_1
941,221670,1726,ŠENTPETER,LJUBLJANA,49,10,LJUBLJANA,ŠMARTINSKA CESTA,24.0,10.0,...,NaN,NaN,NaN,pv 4837/2015,0.0,15.04.2025,14.09.2015,1,1,2015
1318,225324,1722,TRNOVSKO PREDMESTJE,LJUBLJANA,554,6,LJUBLJANA,GERBIČEVA ULICA,49.0,6.0,...,NaN,NaN,NaN,DPN 6056,1.0,15.04.2025,14.10.2015,1,1,2015
2609,225344,1738,DRAVLJE,LJUBLJANA,3317,16,LJUBLJANA,LEDARSKA ULICA,7.0,103.0,...,3.0,NaN,NaN,NaN,0.0,15.04.2025,14.10.2015,1,2,2015
1352,218659,1738,DRAVLJE,LJUBLJANA,3318,25,LJUBLJANA,LEDARSKA ULICA,1.0,111.0,...,NaN,NaN,NaN,NaN,0.0,15.04.2025,18.08.2015,1,2,2015
2012,235571,1737,TABOR,LJUBLJANA,1976,151,LJUBLJANA,VILHARJEVA CESTA,44.0,361.0,...,3.0,NaN,NaN,NaN,0.0,15.04.2025,08.12.2015,1,1,2015
328,231968,1770,KAŠELJ,LJUBLJANA,1118,10,LJUBLJANA,AGROKOMBINATSKA CESTA,3.0,10.0,...,NaN,NaN,NaN,pv 6521/2015,1.0,15.04.2025,16.11.2015,1,1,2015
374,183681,1723,VIČ,LJUBLJANA,9924,36,LJUBLJANA,ULICA ANGELE VODE,13.0,105.0,...,3.0,NaN,NaN,NaN,0.0,23.07.2015,16.01.2015,1,4,2015
1935,235051,1737,TABOR,LJUBLJANA,1976,95,LJUBLJANA,VILHARJEVA CESTA,44.0,305.0,...,3.0,NaN,NaN,NaN,0.0,15.04.2025,02.12.2015,1,1,2015
2574,208728,1732,ŠTEPANJA VAS,LJUBLJANA,362,2,LJUBLJANA,MOŠKRIČEVA ULICA,30.0,2.0,...,NaN,NaN,NaN,NaN,1.0,15.04.2025,15.06.2015,1,1,2015
249,232537,2636,BEŽIGRAD,LJUBLJANA,150,306,LJUBLJANA,GLAVARJEVA ULICA,12.0,306.0,...,NaN,NaN,NaN,PV 6556/2015,1.0,15.04.2025,16.11.2015,1,1,2015

In [12]:
# merge

# 1) Put them in a list
dfs = [df, df1, df2, df3, df4, df5, df6, df7, df8, df9, df0]

# 2) Concatenate into one DataFrame
full_df = pd.concat(dfs, ignore_index=True)

# 3) (Optional) verify
print(full_df.shape)         # rows should equal sum of all individual dfs
print(full_df['LETO'].unique())  # you should see [2014, …, 2024]

(31663, 38)
[2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]

In [13]:
full_df.sample(10)

,ID_POSLA,SIFRA_KO,IME_KO,OBCINA,STEVILKA_STAVBE,STEVILKA_DELA_STAVBE,NASELJE,ULICA,HISNA_STEVILKA,STEVILKA_STANOVANJA_ALI_POSLOVNEGA_PROSTORA,...,STOPNJA_DDV,DATUM_IZTEKA_LIZINGA,DATUM_PRENEHANJA_LIZINGA,OPOMBE_O_PRAVNEM_POSLU,POSREDOVANJE_NEPREMICNINSKE_AGENCIJE,DATUM_ZADNJE_SPREMEMBE_POSLA,DATUM_ZADNJE_UVELJAVITVE_POSLA,VRSTA_AKTA,TRZNOST_POSLA,LETO_1
21180,502554,2680,NOVE JARŠE,LJUBLJANA,289,18,LJUBLJANA,KVEDROVA CESTA,7.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
3200,-673257,1738,DRAVLJE,LJUBLJANA,2360,114,LJUBLJANA,GOTSKA ULICA,10.0,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23258,555562,1736,BRINJE I,LJUBLJANA,951,127,LJUBLJANA,TREBINJSKA ULICA,12.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
24396,653558,1740,SPODNJA ŠIŠKA,LJUBLJANA,600,5,LJUBLJANA,VEROVŠKOVA ULICA,54.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13188,375676,1722,TRNOVSKO PREDMESTJE,LJUBLJANA,3506,1,LJUBLJANA,CESTA DVEH CESARJEV,307.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0
8734,287583,1723,VIČ,LJUBLJANA,2822,4,LJUBLJANA,JAMOVA CESTA,36.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
26592,641553,1735,STOŽICE,LJUBLJANA,322,1,LJUBLJANA,KUŠARJEVA ULICA,11.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24289,649163,2636,BEŽIGRAD,LJUBLJANA,3840,3,LJUBLJANA,ULICA METODA MIKUŽA,20.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14293,391043,1738,DRAVLJE,LJUBLJANA,2245,241,LJUBLJANA,SMRTNIKOVA ULICA,4.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0
14477,378246,1738,DRAVLJE,LJUBLJANA,3141,9,LJUBLJANA,GOTSKA ULICA,12.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0

In [21]:
ko_id = full_df[['SIFRA_KO', 'IME_KO']]

In [22]:
ko_id.head(10)

   SIFRA_KO                IME_KO
0      1772                 SLAPE
1      1727  POLJANSKO PREDMESTJE
2      1723                   VIČ
3      1723                   VIČ
4      1723                   VIČ
5      1723                   VIČ
6      1723                   VIČ
7      1723                   VIČ
8      1723                   VIČ
9      1723                   VIČ

In [24]:
ko_id.drop_duplicates(inplace=True)

C:\Users\gaj\AppData\Local\Temp\ipykernel_31296\1428659597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ko_id.drop_duplicates(inplace=True)

In [25]:
ko_id

      SIFRA_KO                   IME_KO
0         1772                    SLAPE
1         1727     POLJANSKO PREDMESTJE
2         1723                      VIČ
31        1737                    TABOR
33        1736                 BRINJE I
34        1739            ZGORNJA ŠIŠKA
35        1722      TRNOVSKO PREDMESTJE
38        1732             ŠTEPANJA VAS
40        2680               NOVE JARŠE
41        1754    ŠENTVID NAD LJUBLJANO
44        1730                    MOSTE
47        1753                 VIŽMARJE
49        2636                 BEŽIGRAD
51        1733                  BIZOVIK
52        1726                ŠENTPETER
55        1752                STANEŽIČE
57        1756                   ČRNUČE
68        1695     KARLOVŠKO PREDMESTJE
74        1738                  DRAVLJE
75        1740            SPODNJA ŠIŠKA
76        1735                  STOŽICE
79        2679              GRADIŠČE II
81        1770                   KAŠELJ
90        1771                ZADOBROVA
106       1731                    UDMAT
108       1734                   JEŽICA
109       2677                    PRULE
128       2681                BRINJE II
137       1725               AJDOVŠČINA
147       1721               GRADIŠČE I
154       1755                   GLINCE
157       1759                PODGORICA
167       1728          LJUBLJANA MESTO
263       1750  ŠMARTNO POD ŠMARNO GORO
436       1720     KRAKOVSKO PREDMESTJE
453       2682                     BRDO
496       2706              ZELENA JAMA
632       1994                  DOBROVA
654       1749                 GAMELJNE
688       1982                   ŠUJICA
692       1701                IŠKA LOKA
855       1773                 DOBRUNJE
882       1995                PODSMREKA
1047      1729          ŠMARTNO OB SAVI
1120      1775                   SOSTRO
1128      1777                    JAVOR
1157      1751                    TACEN
1249      1778                 VOLAVLJE
1469      1696                   RUDNIK
1682      1776                 LIPOGLAV
1723      1757                NADGORICA
2406      2678                  GOLOVEC
2817      1774                PODMOLNIK
2832      2683                     GRIČ
3522      1702                 TOMIŠELJ
3591      1746                   RAŠICA
6782      1779               TREBELJEVO

In [26]:
ko_id.to_csv(r"ko_id.csv", sep=",", encoding="utf-8", index=False)